// Auto-generated by deploy-challenge.js
export const CHALLENGE_CONTRACT_ADDRESS = '0x22aC931d73351a33CeD412155999cd4945984184';

export const CHALLENGE_ABI = [
    "function submitChallenge(uint256 _marketId, bool _isRed, string calldata _title, string calldata _evidence, uint256 _replyToId) external returns (uint256)",
    "function getMarketChallengeCount(uint256 _marketId) external view returns (uint256)",
    "function getMarketChallengeIds(uint256 _marketId, uint256 _offset, uint256 _limit) external view returns (uint256[])",
    "function getChallenge(uint256 _challengeId) external view returns (uint256 id, uint256 marketId, uint8 cType, address author, string title, string evidence, uint256 timestamp, uint256 replyToId)",
    "function challengeCount() view returns (uint256)"
];
